-- AlterTable
ALTER TABLE "User" ADD COLUMN     "muxJwt" TEXT,
ADD COLUMN     "muxJwtCreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "viewerCount" INTEGER NOT NULL DEFAULT 0;
